# frozen_string_literal: true

require 'legion/extensions/service_now/version'
require 'legion/extensions/service_now/errors'
require 'legion/extensions/service_now/helpers/client'
require 'legion/extensions/service_now/helpers/pagination'
require 'legion/extensions/service_now/helpers/retry'

require 'legion/extensions/service_now/change/runners/change'
require 'legion/extensions/service_now/cmdb/instance/runners/instance'
require 'legion/extensions/service_now/cmdb/meta/runners/meta'
require 'legion/extensions/service_now/knowledge/runners/knowledge'
require 'legion/extensions/service_now/service_catalog/runners/service_catalog'
require 'legion/extensions/service_now/account/runners/account'
require 'legion/extensions/service_now/incident/runners/incident'
require 'legion/extensions/service_now/problem/runners/problem'
require 'legion/extensions/service_now/attachment/runners/attachment'
require 'legion/extensions/service_now/table/runners/table'
require 'legion/extensions/service_now/aggregate/runners/aggregate'
require 'legion/extensions/service_now/user/runners/user'
require 'legion/extensions/service_now/user_group/runners/user_group'
require 'legion/extensions/service_now/request/runners/request'
require 'legion/extensions/service_now/approval/runners/approval'
require 'legion/extensions/service_now/task/runners/task'
require 'legion/extensions/service_now/sla/runners/sla'
require 'legion/extensions/service_now/import_set/runners/import_set'
require 'legion/extensions/service_now/event/runners/event'
require 'legion/extensions/service_now/performance_analytics/runners/performance_analytics'
require 'legion/extensions/service_now/flow/runners/flow'
require 'legion/extensions/service_now/notification/runners/notification'
require 'legion/extensions/service_now/email_log/runners/email_log'
require 'legion/extensions/service_now/audit/runners/audit'
require 'legion/extensions/service_now/system_property/runners/system_property'
require 'legion/extensions/service_now/asset/runners/asset'
require 'legion/extensions/service_now/location/runners/location'
require 'legion/extensions/service_now/department/runners/department'
require 'legion/extensions/service_now/company/runners/company'
require 'legion/extensions/service_now/project/runners/project'
require 'legion/extensions/service_now/release/runners/release'
require 'legion/extensions/service_now/hr_case/runners/hr_case'
require 'legion/extensions/service_now/security_incident/runners/security_incident'
require 'legion/extensions/service_now/update_set/runners/update_set'
require 'legion/extensions/service_now/script_include/runners/script_include'
require 'legion/extensions/service_now/business_rule/runners/business_rule'
require 'legion/extensions/service_now/scheduled_job/runners/scheduled_job'
require 'legion/extensions/service_now/on_call/runners/on_call'
require 'legion/extensions/service_now/survey/runners/survey'
require 'legion/extensions/service_now/contract/runners/contract'
require 'legion/extensions/service_now/cost_center/runners/cost_center'
require 'legion/extensions/service_now/work_order/runners/work_order'
require 'legion/extensions/service_now/discovery/runners/discovery'
require 'legion/extensions/service_now/mid_server/runners/mid_server'
require 'legion/extensions/service_now/catalog_variable/runners/catalog_variable'
require 'legion/extensions/service_now/workflow/runners/workflow'
require 'legion/extensions/service_now/vendor/runners/vendor'
require 'legion/extensions/service_now/ci_relationship/runners/ci_relationship'
require 'legion/extensions/service_now/script_action/runners/script_action'
require 'legion/extensions/service_now/ui_policy/runners/ui_policy'
require 'legion/extensions/service_now/ui_action/runners/ui_action'
require 'legion/extensions/service_now/access_control/runners/access_control'
require 'legion/extensions/service_now/catalog_task/runners/catalog_task'
require 'legion/extensions/service_now/knowledge_base/runners/knowledge_base'
require 'legion/extensions/service_now/tag/runners/tag'
require 'legion/extensions/service_now/metric/runners/metric'
require 'legion/extensions/service_now/currency/runners/currency'
require 'legion/extensions/service_now/calendar/runners/calendar'
require 'legion/extensions/service_now/knowledge_feedback/runners/knowledge_feedback'
require 'legion/extensions/service_now/license/runners/license'
require 'legion/extensions/service_now/deprecation_log/runners/deprecation_log'
require 'legion/extensions/service_now/cmdb_health/runners/cmdb_health'

require 'legion/extensions/service_now/client'

if defined?(Legion::LLM)
  require 'legion/extensions/service_now/skills/incident'
  require 'legion/extensions/service_now/skills/change_request'
  require 'legion/extensions/service_now/skills/cmdb_query'
  require 'legion/extensions/service_now/skills/knowledge'
  require 'legion/extensions/service_now/skills/service_catalog'
  require 'legion/extensions/service_now/skills/problem_management'
  require 'legion/extensions/service_now/skills/request_fulfillment'
  require 'legion/extensions/service_now/skills/approval_workflow'
  require 'legion/extensions/service_now/skills/asset_management'
  require 'legion/extensions/service_now/skills/security_incident_response'
end

module Legion
  module Extensions
    module ServiceNow
      extend Legion::Extensions::Core if Legion::Extensions.const_defined? :Core
    end
  end
end
